project:
  type: default
  output-dir: ../outputs/report

format:
  html:
    toc: true
    toc-depth: 3
    number-sections: true
  docx:
    toc: true
    toc-depth: 3
    number-sections: true

execute:
  echo: false
  warning: false
  message: false
