data:
  excel_path: data/raw/survey_master_cleaned_v1.xlsx
  sheet: 1
vars:
  region: region
  district: district
  age: age
  gender: 1.2. Респондент жинси
  education: '1.4. Маълумотингиз:'
  hh_income: 1.10. Уй хўжалигингиз аъзоларининг жами ойлик даромади?
  income_earners: 1.7. Уй хўжалигингизда неча киши даромадли меҳнат (иш) билан банд?
  credit_type: kredit_turi
  payment_status: holat1
  extra_funds_source: 2.2. Қўшимча маблағ зарур бўлганда биринчи бўлиб қаерга ёки
    кимга мурожаат қиласиз?
  debt_burden_share: 2.4.2. Таҳминан оилавий даромадингизнинг қанча қисми (неча фоизи)
    қарзни қайтариш учун сарфланади?
  income_volatility: 2.4.4. Даромадингиз ойма-ой қай даражада ўзгариб туради?
  read_contract: 3.4. Қарз (кредит, насия) олишдан аввал тузилган шартнома билан танишганмисиз?
  loan_purpose_main: 2.7. Ушбу қарзни (кредит, насия) олишда асосий мақсад нима бўлган?
blocks:
  late_payment_reasons_prefix: 3.7. Нима сабабдан қарз (кредит, насия) ўз вақтида
    амалга ошириш имконияти мавжуд бўлмаган?/
